version: '3.8'

services:
  elasticsearch:
    image: elasticsearch:9.0.1
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false

  melodic-search:
    build: .
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT=9200
      - FLASK_ENV=production
    ports:
      - "5000:5000"
    restart: unless-stopped
